### PR TITLE
Incorporate objective fix

### PR DESCRIPTION
**Pull request by simon33-2**
Incorporate PR num11 from ww2_global

### CODE REVIEW

**Comment by DanVanAtta** [comment]
config file has been moved back to the game engine: https://github.com/triplea-game/triplea/blob/master/triplea_maps.yaml

Has this update already been applied, looks updated over there.

**Comment by simon33-2** [comment]
Seems so.

Does this mean that it is going to be harder to update the maps then? I don't think I understood that aspect of getting rid of this repo.

But I'll close the PR.

**Comment by DanVanAtta** [comment]
Should be same difficulty I hope, just new location. 
This repo is a bit weird. At the very least I want to move the live game file to where the live game files are.

**Comment by DanVanAtta** [comment]
Plus the game engine repo is set up with a travis build already, in case we want to do post-processing on the map list, that will be convenient to have in place already.

**Pull request closed without merging**
